# Generated by Django 5.0.6 on 2024-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Бренд')),
                ('image', models.FileField(blank=True, null=True, upload_to='main/static/main/img', verbose_name='Фото автомобиля')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('fabrication', models.DateField(verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(verbose_name='Пробег, км')),
                ('price', models.IntegerField(verbose_name='Цена, р')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
