# Generated by Django 5.0.6 on 2024-06-13 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='automobils/static/automobils/img', verbose_name='Фото автомобиля'),
        ),
    ]
