# Generated by Django 5.0.6 on 2024-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobils', '0003_favoritead'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritead',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favoritead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
