# Generated by Django 5.1.4 on 2025-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicalclient_historicalreview_historicalsalon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
    ]
